---
- hosts: default
  become: true

  vars:
    aws_access_key_id: '{{ lookup("env","AWS_ACCESS_KEY_ID") }}'
    aws_secret_access_key: '{{ lookup("env","AWS_SECRET_ACCESS_KEY") }}'
    aws_default_region: '{{ lookup("env","AWS_DEFAULT_REGION") }}'
    s3_bucket_name: '{{ lookup("env","S3_BUCKET_NAME") }}'
    poudriere_build_options_file: 'make.conf'
    poudriere_port_list_file: './files/port.list'
    poudriere_key_file: '{{ lookup("env","POUDRIERE_KEY_FILE") }}'
    poudriere_jails:
    - { jail_name: 'freebsd-10_2_x64', version: '10.2-RELEASE' }
    - { jail_name: 'freebsd-11_1_x64', version: '11.1-RELEASE' }
    - { jail_name: 'freebsd-11_2_x64', version: '11.2-RELEASE' }

  roles:
  - { role: JoergFiedler.freebsd-build-server }
