---
- hosts: all
  become: true

  vars:
    aws_access_key_id: '{{ lookup("env","AWS_ACCESS_KEY_ID") }}'
    aws_secret_access_key: '{{ lookup("env","AWS_SECRET_ACCESS_KEY") }}'
    aws_default_region: '{{ lookup("env","AWS_DEFAULT_REGION") }}'
    s3_bucket_name: '{{ lookup("env","S3_BUCKET_NAME") }}'
    poudriere_build_options_file: 'make.conf'
    poudriere_ports_list_file: './files/ports.list'
    poudriere_ports_branch_name: 'branches/2020Q4'
    poudriere_key_file: '{{ lookup("env","POUDRIERE_KEY_FILE") }}'
    poudriere_zpool: 'tank'
    poudriere_jails:
    - { jail_name: 'freebsd-11_3_x64', version: '11.3-RELEASE' }
    - { jail_name: 'freebsd-12_1_x64', version: '12.1-RELEASE' }

  roles:
    - JoergFiedler.freebsd-build-server
